// src/web/src/pages/AddWatchPage.tsx
import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { createWatch, uploadWatchImages, getWatches } from '../api/watches';
import WatchForm from '../components/WatchForm';
import type { CreateWatch } from '../types';

export default function AddWatchPage() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [brands, setBrands] = useState<string[]>([]);

  const initialBrand = searchParams.get('brand') ?? '';
  const initialModel = searchParams.get('model') ?? '';

  useEffect(() => {
    getWatches().then((watches) => {
      const unique = [...new Set(watches.map((w) => w.brand))].sort();
      setBrands(unique);
    }).catch(() => {});
  }, []);

  async function handleSubmit(data: CreateWatch, files: File[]) {
    try {
      const watch = await createWatch(data);
      if (files.length > 0) {
        await uploadWatchImages(watch.id, files);
      }
      navigate(`/watches/${watch.id}`);
    } catch (error) {
      console.error('Failed to create watch:', error);
      alert('Failed to create watch. Please try again.');
    }
  }

  return (
    <div className="watch-form-page">
      <h1>Add Watch</h1>
      <WatchForm
        initial={initialBrand ? { brand: initialBrand, model: initialModel } : undefined}
        onSubmit={handleSubmit}
        submitLabel="Add Watch"
        onCancel={() => navigate('/')}
        brands={brands}
      />
    </div>
  );
}

// src/web/src/pages/AddWatchPage.vue
<template>
  <div>
    <h2 class="font-display text-2xl font-semibold text-text mb-6">Add Watch</h2>
    <WatchForm @submit="handleSubmit" :loading="loading" :existing-brands="brands" />
    <p v-if="error" class="text-danger text-sm mt-4">{{ error }}</p>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { createWatch, getWatches, uploadImage } from '@/services/watches'
import WatchForm from '@/components/common/WatchForm.vue'
import type { CreateWatch } from '@/types'

const router = useRouter()
const loading = ref(false)
const error = ref('')
const brands = ref<string[]>([])

onMounted(async () => {
  try {
    const watches = await getWatches()
    brands.value = [...new Set(watches.map(w => w.brand))].sort()
  } catch { /* non-critical */ }
})

async function handleSubmit(data: CreateWatch, photo?: File) {
  loading.value = true
  error.value = ''
  try {
    const watch = await createWatch(data)
    if (photo) {
      await uploadImage(watch.id, photo)
    }
    router.push(`/watches/${watch.id}`)
  } catch (e: any) {
    error.value = e.response?.data?.error || 'Failed to create watch'
  } finally {
    loading.value = false
  }
}
</script>
