// src/web/src/pages/EditWatchPage.tsx
import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getWatch, updateWatch, uploadWatchImages } from '../api/watches';
import WatchForm from '../components/WatchForm';
import type { Watch, CreateWatch } from '../types';

export default function EditWatchPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [watch, setWatch] = useState<Watch | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) return;
    getWatch(Number(id))
      .then(setWatch)
      .catch(() => navigate('/'))
      .finally(() => setLoading(false));
  }, [id, navigate]);

  async function handleSubmit(data: CreateWatch, files: File[]) {
    if (!id) return;
    await updateWatch(Number(id), data);
    if (files.length > 0) {
      await uploadWatchImages(Number(id), files);
    }
    navigate(`/watches/${id}`);
  }

  if (loading) return <p>Loading…</p>;
  if (!watch) return <p>Watch not found.</p>;

  return (
    <div>
      <h1>Edit {watch.brand} {watch.model}</h1>
      <WatchForm initial={watch} onSubmit={handleSubmit} submitLabel="Update Watch" />
    </div>
  );
}

// src/web/src/pages/EditWatchPage.vue
<template>
  <div>
    <h2 class="font-display text-2xl font-semibold text-text mb-6">Edit Watch</h2>
    <div v-if="loading" class="flex justify-center py-20">
      <div class="w-8 h-8 border-2 border-accent border-t-transparent rounded-full animate-spin" />
    </div>
    <WatchForm v-else-if="watch" :initial="watch" @submit="handleSubmit" :loading="saving" />
    <p v-if="error" class="text-danger text-sm mt-4">{{ error }}</p>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { getWatch, updateWatch } from '@/services/watches'
import WatchForm from '@/components/common/WatchForm.vue'
import type { Watch, UpdateWatch } from '@/types'

const route = useRoute()
const router = useRouter()
const watch = ref<Watch | null>(null)
const loading = ref(true)
const saving = ref(false)
const error = ref('')

onMounted(async () => {
  try {
    watch.value = await getWatch(Number(route.params.id))
  } finally {
    loading.value = false
  }
})

async function handleSubmit(data: UpdateWatch) {
  if (!watch.value) return
  saving.value = true
  error.value = ''
  try {
    await updateWatch(watch.value.id, data)
    router.push(`/watches/${watch.value.id}`)
  } catch (e: any) {
    error.value = e.response?.data?.error || 'Failed to update watch'
  } finally {
    saving.value = false
  }
}
</script>
