// src/web/src/pages/StatsPage.tsx
import { useEffect, useMemo, useRef, useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { getWearLogs, deleteWearLog, updateWearLogDate, getWatches } from '../api/watches';
import ConfirmDialog from '../components/ConfirmDialog';
import { usePreferences } from '../context/PreferencesContext';
import useIsPwa from '../hooks/useIsPwa';
import type { WearLog, Watch } from '../types';

const CLOUD_VAR_COUNT = 10;

interface CloudWord {
  text: string;
  count: number;
  size: number;
  colorVar: string;
  opacity: number;
}

export default function StatsPage() {
  const [logs, setLogs] = useState<WearLog[]>([]);
  const [watches, setWatches] = useState<Watch[]>([]);
  const [loading, setLoading] = useState(true);
  const { timezone } = usePreferences();
  const isPwa = useIsPwa();

  useEffect(() => {
    Promise.all([
      getWearLogs().catch(() => [] as WearLog[]),
      getWatches().catch(() => [] as Watch[]),
    ]).then(([wearLogs, allWatches]) => {
      setLogs(wearLogs);
      setWatches(allWatches);
    }).finally(() => setLoading(false));
  }, []);

  const topExpensive = useMemo(() => {
    return watches
      .filter((w) => !w.isWishList && !w.isRetired && w.purchasePrice != null && w.purchasePrice > 0)
      .sort((a, b) => (b.purchasePrice ?? 0) - (a.purchasePrice ?? 0))
      .slice(0, 5);
  }, [watches]);

  const { longestUnworn, neverWorn } = useMemo(() => {
    const now = new Date();
    const collection = watches.filter((w) => !w.isWishList && !w.isRetired);
    const worn = collection
      .filter((w) => w.lastWornDate)
      .map((w) => ({
        watch: w,
        daysSince: Math.floor((now.getTime() - new Date(w.lastWornDate!).getTime()) / 86_400_000),
      }))
      .sort((a, b) => b.daysSince - a.daysSince)
      .slice(0, 5);
    const never = collection.filter((w) => !w.lastWornDate);
    return { longestUnworn: worn, neverWorn: never };
  }, [watches]);

  const words: CloudWord[] = useMemo(() => {
    const counts: Record<string, number> = {};
    for (const log of logs) {
      const key = `${log.watchBrand} ${log.watchModel}`;
      counts[key] = (counts[key] ?? 0) + 1;
    }

    const entries = Object.entries(counts).sort((a, b) => b[1] - a[1]);
    if (entries.length === 0) return [];

    const max = entries[0][1];
    const min = entries[entries.length - 1][1];
    const minSize = 0.9;
    const maxSize = 3;

    return entries.map(([text, count], i) => {
      const ratio = max === min ? 1 : (count - min) / (max - min);
      const size = minSize + ratio * (maxSize - minSize);
      const opacity = 0.5 + ratio * 0.5;
      return {
        text,
        count,
        size,
        colorVar: `var(--cloud-${(i % CLOUD_VAR_COUNT) + 1})`,
        opacity,
      };
    });
  }, [logs]);

  // Shuffle words for a natural cloud layout
  const shuffledWords = useMemo(() => {
    const arr = [...words];
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  }, [words]);

  const totalWears = logs.length;
  const uniqueWatches = new Set(logs.map((l) => l.watchId)).size;

  const timeline = logs;

  function fmtDate(iso: string) {
    return new Date(iso).toLocaleDateString('en-US', { timeZone: timezone, month: 'short', day: 'numeric', year: 'numeric' });
  }

  const [pendingDeleteLogId, setPendingDeleteLogId] = useState<number | null>(null);

  const doDeleteLog = useCallback(async (logId: number) => {
    try {
      await deleteWearLog(logId);
      setLogs((prev) => prev.filter((l) => l.id !== logId));
    } catch { /* ignore */ }
  }, []);

  async function handleDeleteLog(logId: number) {
    setPendingDeleteLogId(logId);
  }

  const dateInputRefs = useRef<Record<number, HTMLInputElement | null>>({});

  function resetDateInput(logId: number) {
    const input = dateInputRefs.current[logId];
    if (input) {
      input.style.position = '';
      input.style.opacity = '';
      input.style.pointerEvents = '';
      input.style.width = '';
      input.style.height = '';
      input.style.clip = '';
    }
  }

  async function handleDateChange(logId: number, newDate: string) {
    resetDateInput(logId);
    if (!newDate) return;
    try {
      await updateWearLogDate(logId, newDate);
      setLogs((prev) =>
        prev.map((l) => l.id === logId ? { ...l, wornDate: newDate } : l)
          .sort((a, b) => new Date(b.wornDate).getTime() - new Date(a.wornDate).getTime())
      );
    } catch { /* ignore */ }
  }

  if (loading) return <p>Loading…</p>;

  return (
    <div className="stats-page">
      <div className="page-header">
        <h1>Wear Stats</h1>
        {!isPwa && <Link to="/" className="btn btn-sm">← Back</Link>}
      </div>

      <div className="stats-summary">
        <div className="stats-summary-card">
          <span className="stats-summary-value">{totalWears}</span>
          <span className="stats-summary-label">Total Wears</span>
        </div>
        <div className="stats-summary-card">
          <span className="stats-summary-value">{uniqueWatches}</span>
          <span className="stats-summary-label">Watches Worn</span>
        </div>
      </div>

      {topExpensive.length > 0 && (
        <section className="stats-section">
          <h2>Most Valuable</h2>
          <div className="top-expensive-list">
            {topExpensive.map((w, i) => (
              <Link key={w.id} to={`/watches/${w.id}`} className="top-expensive-item">
                <span className="top-expensive-rank">#{i + 1}</span>
                <span className="top-expensive-name">{w.brand} {w.model}</span>
                <span className="top-expensive-price">${w.purchasePrice!.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
              </Link>
            ))}
          </div>
        </section>
      )}

      {(longestUnworn.length > 0 || neverWorn.length > 0) && (
        <section className="stats-section">
          <h2>Neglected Watches</h2>
          <div className="neglected-split">
            {longestUnworn.length > 0 && (
              <div className="neglected-column">
                <h3>Longest Since Worn</h3>
                <div className="top-expensive-list">
                  {longestUnworn.map((item, i) => (
                    <Link key={item.watch.id} to={`/watches/${item.watch.id}`} className="top-expensive-item">
                      <span className="top-expensive-rank">#{i + 1}</span>
                      <span className="top-expensive-name">{item.watch.brand} {item.watch.model}</span>
                      <span className="neglected-days">{item.daysSince}d ago</span>
                    </Link>
                  ))}
                </div>
              </div>
            )}
            {neverWorn.length > 0 && (
              <div className="neglected-column">
                <h3>Never Worn</h3>
                <div className="top-expensive-list">
                  {neverWorn.map((w) => (
                    <Link key={w.id} to={`/watches/${w.id}`} className="top-expensive-item">
                      <span className="top-expensive-name">{w.brand} {w.model}</span>
                    </Link>
                  ))}
                </div>
              </div>
            )}
          </div>
        </section>
      )}

      <section className="stats-section">
        <h2>Wear Cloud</h2>
        {shuffledWords.length === 0 ? (
          <p className="stats-empty">No wear events recorded yet. Hit "Wore Today" on a watch to get started!</p>
        ) : (
          <div className="word-cloud">
            {shuffledWords.map((w) => (
              <span
                key={w.text}
                className="word-cloud-word"
                style={{
                  fontSize: `${w.size}rem`,
                  color: w.colorVar,
                  opacity: w.opacity,
                }}
                title={`${w.text}: worn ${w.count} time${w.count !== 1 ? 's' : ''}`}
              >
                {w.text}
              </span>
            ))}
          </div>
        )}
      </section>

      <section className="stats-section">
        <h2>Recent Wear Timeline</h2>
        {timeline.length === 0 ? (
          <p className="stats-empty">No wear events recorded yet.</p>
        ) : (
          <div className="wear-timeline">
            {timeline.map((log) => (
              <div key={log.id} className="wear-timeline-entry">
                <span className="wear-timeline-dot" />
                <Link to={`/watches/${log.watchId}`} className="wear-timeline-content">
                  <strong>{log.watchBrand} {log.watchModel}</strong>
                  <span className="wear-timeline-date">{fmtDate(log.wornDate)}</span>
                </Link>
                <input
                  type="date"
                  ref={(el) => { dateInputRefs.current[log.id] = el; }}
                  className="wear-timeline-date-input"
                  value={log.wornDate.slice(0, 10)}
                  onChange={(e) => handleDateChange(log.id, e.target.value)}
                  onBlur={() => resetDateInput(log.id)}
                />
                <button
                  className="wear-timeline-edit"
                  onClick={() => {
                    const input = dateInputRefs.current[log.id];
                    if (!input) return;
                    input.style.position = 'absolute';
                    input.style.opacity = '0';
                    input.style.pointerEvents = 'auto';
                    input.style.width = 'auto';
                    input.style.height = 'auto';
                    input.style.clip = 'auto';
                    input.focus();
                    input.click();
                    try { input.showPicker(); } catch { /* not supported */ }
                  }}
                  title="Change date"
                >
                  ✎
                </button>
                <button
                  className="wear-timeline-delete"
                  onClick={() => handleDeleteLog(log.id)}
                  title="Remove this wear entry"
                >
                  ✕
                </button>
              </div>
            ))}
          </div>
        )}
      </section>
      <ConfirmDialog
        open={pendingDeleteLogId !== null}
        title="Remove Wear Entry"
        message="Are you sure you want to remove this wear entry?"
        confirmLabel="Remove"
        variant="danger"
        onConfirm={() => { if (pendingDeleteLogId !== null) doDeleteLog(pendingDeleteLogId); setPendingDeleteLogId(null); }}
        onCancel={() => setPendingDeleteLogId(null)}
      />
    </div>
  );
}

// src/web/src/pages/StatsPage.vue
<template>
  <div>
    <PullToRefresh :pulling="pulling" :refreshing="refreshing" :pull-distance="pullDistance" />
    <h2 class="font-display text-2xl font-semibold text-text mb-6">Statistics</h2>

    <div v-if="loading" class="flex items-center justify-center py-20">
      <div class="w-8 h-8 border-2 border-accent border-t-transparent rounded-full animate-spin" />
    </div>

    <div v-else-if="error" class="text-center py-20">
      <p class="text-danger mb-2">Failed to load statistics</p>
      <button @click="load" class="text-accent text-sm hover:underline">Retry</button>
    </div>

    <div v-else class="space-y-8">
      <!-- Summary Cards -->
      <div class="grid grid-cols-2 lg:grid-cols-3 gap-4">
        <div class="bg-bg-card border border-border rounded-xl p-4 text-center">
          <p class="text-3xl font-display font-semibold text-accent">{{ watches.length }}</p>
          <p class="text-sm text-text-secondary mt-1">Total Watches</p>
        </div>
        <div class="bg-bg-card border border-border rounded-xl p-4 text-center">
          <p class="text-3xl font-display font-semibold text-accent">{{ totalWears }}</p>
          <p class="text-sm text-text-secondary mt-1">Total Wears</p>
        </div>
        <div class="bg-bg-card border border-border rounded-xl p-4 text-center col-span-2 lg:col-span-1">
          <p class="text-3xl font-display font-semibold text-accent">{{ avgWears }}</p>
          <p class="text-sm text-text-secondary mt-1">Avg Wears / Watch</p>
        </div>
      </div>

      <!-- Movement Type Breakdown -->
      <div class="bg-bg-card border border-border rounded-xl p-4">
        <h3 class="text-lg font-medium text-text mb-4">Movement Types</h3>
        <div v-if="movementBreakdown.length === 0" class="text-sm text-text-muted">No data</div>
        <div v-else class="space-y-3">
          <div v-for="item in movementBreakdown" :key="item.type" class="flex items-center gap-3">
            <span
              class="inline-block w-3 h-3 rounded-full flex-shrink-0"
              :class="movementColor(item.type)"
            />
            <span class="text-sm text-text flex-1">{{ item.type }}</span>
            <span class="px-3 py-1.5 bg-bg-surface border border-border rounded-full text-xs text-text-secondary">
              {{ item.count }} ({{ item.pct }}%)
            </span>
          </div>
        </div>
      </div>

      <!-- Most Popular Brands -->
      <div class="bg-bg-card border border-border rounded-xl p-4">
        <h3 class="text-lg font-medium text-text mb-4">Top Brands</h3>
        <div v-if="brandBreakdown.length === 0" class="text-sm text-text-muted">No data</div>
        <div v-else class="space-y-3">
          <div v-for="(item, i) in brandBreakdown" :key="item.brand" class="flex items-center gap-3">
            <span class="text-sm font-medium text-accent w-5 text-right flex-shrink-0">{{ i + 1 }}.</span>
            <div class="flex-1 min-w-0">
              <div class="flex items-center justify-between mb-1">
                <span class="text-sm text-text truncate">{{ item.brand }}</span>
                <span class="text-xs text-text-muted flex-shrink-0 ml-2">{{ item.count }} watch{{ item.count > 1 ? 'es' : '' }}</span>
              </div>
              <div class="h-1.5 bg-bg-surface rounded-full overflow-hidden">
                <div class="h-full bg-accent/60 rounded-full transition-all" :style="{ width: item.pct + '%' }" />
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Most Worn -->
      <div class="bg-bg-card border border-border rounded-xl p-4">
        <h3 class="text-lg font-medium text-text mb-4">Most Worn</h3>
        <div v-if="mostWorn.length === 0" class="text-sm text-text-muted">No wear data yet</div>
        <div v-else class="space-y-3">
          <RouterLink
            v-for="(w, i) in mostWorn"
            :key="w.id"
            :to="`/watches/${w.id}`"
            class="flex items-center gap-3 group"
          >
            <span class="text-sm font-medium text-accent w-5 text-right">{{ i + 1 }}.</span>
            <div class="w-10 h-10 rounded-lg bg-bg-surface overflow-hidden flex-shrink-0">
              <img v-if="w.imageUrls.length" :src="imageUrl(w.imageUrls[0].url)" class="w-full h-full object-contain" />
              <span v-else class="flex items-center justify-center w-full h-full text-text-muted text-lg">⌚</span>
            </div>
            <div class="flex-1 min-w-0">
              <p class="text-sm text-text truncate group-hover:text-accent transition-colors">{{ w.brand }} {{ w.model }}</p>
            </div>
            <span class="text-sm text-text-secondary">{{ w.timesWorn }}×</span>
          </RouterLink>
        </div>
      </div>

      <!-- Neglected Watches -->
      <div class="bg-bg-card border border-border rounded-xl p-4">
        <h3 class="text-lg font-medium text-text mb-4">Neglected (30+ days)</h3>
        <div v-if="neglected.length === 0" class="text-sm text-text-muted">All watches are getting love! 🎉</div>
        <div v-else class="space-y-3">
          <RouterLink
            v-for="w in neglected"
            :key="w.id"
            :to="`/watches/${w.id}`"
            class="flex items-center gap-3 group"
          >
            <div class="w-10 h-10 rounded-lg bg-bg-surface overflow-hidden flex-shrink-0">
              <img v-if="w.imageUrls.length" :src="imageUrl(w.imageUrls[0].url)" class="w-full h-full object-contain" />
              <span v-else class="flex items-center justify-center w-full h-full text-text-muted text-lg">⌚</span>
            </div>
            <div class="flex-1 min-w-0">
              <p class="text-sm text-text truncate group-hover:text-accent transition-colors">{{ w.brand }} {{ w.model }}</p>
              <p class="text-xs text-text-muted">
                {{ w.lastWornDate ? `Last worn ${daysSince(w.lastWornDate)} days ago` : 'Never worn' }}
              </p>
            </div>
          </RouterLink>
        </div>
      </div>

      <!-- Recent Activity -->
      <div class="bg-bg-card border border-border rounded-xl p-4">
        <h3 class="text-lg font-medium text-text mb-4">Recent Activity</h3>
        <div v-if="recentLogs.length === 0" class="text-sm text-text-muted">No wear logs yet</div>
        <div v-else class="relative max-h-[320px] overflow-y-auto">
          <!-- Timeline line -->
          <div class="absolute left-[15px] top-2 bottom-2 w-px bg-border" />
          <div class="space-y-4">
            <RouterLink
              v-for="(log, i) in recentLogs"
              :key="log.id"
              :to="`/watches/${log.watchId}`"
              class="flex items-start gap-4 group relative"
            >
              <!-- Timeline dot -->
              <div class="relative z-10 flex-shrink-0 mt-1">
                <div
                  class="w-[9px] h-[9px] rounded-full border-2 transition-colors ml-[11px]"
                  :class="i === 0 ? 'bg-accent border-accent' : 'bg-bg-card border-text-muted group-hover:border-accent'"
                />
              </div>
              <!-- Card -->
              <div class="flex-1 flex items-center gap-3 px-3 py-2.5 rounded-lg bg-bg-surface/50 border border-transparent group-hover:border-accent/30 transition-all">
                <div class="flex-1 min-w-0">
                  <p class="text-sm text-text font-medium truncate group-hover:text-accent transition-colors">
                    {{ log.watchBrand }} {{ log.watchModel }}
                  </p>
                  <p class="text-xs text-text-muted mt-0.5">{{ formatRelativeDate(log.wornDate) }}</p>
                </div>
                <span class="text-xs text-text-muted flex-shrink-0">{{ formatDate(log.wornDate) }}</span>
              </div>
            </RouterLink>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import type { Watch, WearLog } from '@/types'
import { getWatches, getWearLogs, imageUrl } from '@/services/watches'
import { usePullToRefresh } from '@/composables/usePullToRefresh'
import PullToRefresh from '@/components/common/PullToRefresh.vue'

const { refreshing, pullDistance, pulling } = usePullToRefresh(load)

const watches = ref<Watch[]>([])
const wearLogs = ref<WearLog[]>([])
const loading = ref(true)
const error = ref(false)

const totalWears = computed(() => watches.value.reduce((sum, w) => sum + w.timesWorn, 0))
const avgWears = computed(() => watches.value.length ? (totalWears.value / watches.value.length).toFixed(1) : '0')

const mostWorn = computed(() =>
  [...watches.value].filter(w => w.timesWorn > 0).sort((a, b) => b.timesWorn - a.timesWorn).slice(0, 5)
)

const neglected = computed(() => {
  const threshold = Date.now() - 30 * 24 * 60 * 60 * 1000
  return watches.value.filter(w => {
    if (!w.lastWornDate) return true
    return new Date(w.lastWornDate).getTime() < threshold
  }).sort((a, b) => {
    if (!a.lastWornDate) return -1
    if (!b.lastWornDate) return 1
    return new Date(a.lastWornDate).getTime() - new Date(b.lastWornDate).getTime()
  })
})

const movementBreakdown = computed(() => {
  const counts: Record<string, number> = {}
  watches.value.forEach(w => { counts[w.movementType] = (counts[w.movementType] || 0) + 1 })
  const total = watches.value.length || 1
  return Object.entries(counts)
    .map(([type, count]) => ({ type, count, pct: Math.round((count / total) * 100) }))
    .sort((a, b) => b.count - a.count)
})

const brandBreakdown = computed(() => {
  const counts: Record<string, number> = {}
  watches.value.forEach(w => { counts[w.brand] = (counts[w.brand] || 0) + 1 })
  const max = Math.max(...Object.values(counts), 1)
  return Object.entries(counts)
    .map(([brand, count]) => ({ brand, count, pct: Math.round((count / max) * 100) }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 5)
})

const recentLogs = computed(() => [...wearLogs.value].sort((a, b) => new Date(b.wornDate).getTime() - new Date(a.wornDate).getTime()).slice(0, 10))

function movementColor(type: string): string {
  const map: Record<string, string> = {
    Automatic: 'bg-accent',
    Manual: 'bg-success',
    Quartz: 'bg-blue-400',
    Digital: 'bg-purple-400',
  }
  return map[type] || 'bg-text-muted'
}

function daysSince(dateStr: string): number {
  // Parse as local date to avoid timezone offset issues with date-only strings
  const parts = dateStr.split('T')[0].split('-')
  const d = new Date(Number(parts[0]), Number(parts[1]) - 1, Number(parts[2]))
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  return Math.floor((today.getTime() - d.getTime()) / (1000 * 60 * 60 * 24))
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })
}

function formatRelativeDate(dateStr: string): string {
  const days = daysSince(dateStr)
  if (days === 0) return 'Today'
  if (days === 1) return 'Yesterday'
  if (days < 7) return `${days} days ago`
  if (days < 14) return '1 week ago'
  return `${Math.floor(days / 7)} weeks ago`
}

async function load() {
  loading.value = true
  error.value = false
  try {
    const [allWatches, logs] = await Promise.all([getWatches(), getWearLogs()])
    watches.value = allWatches.filter(w => !w.isRetired && !w.isWishList)
    wearLogs.value = logs
  } catch {
    error.value = true
  } finally {
    loading.value = false
  }
}

onMounted(load)
</script>
