// src/web/src/pages/WatchDetailPage.tsx
import { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import Markdown from 'react-markdown';
import { getWatch, deleteWatch, deleteWatchImage, analyzeWatch, updateWatch, recordWear } from '../api/watches';
import ImageCarousel from '../components/ImageCarousel';
import { usePreferences } from '../context/PreferencesContext';
import type { Watch } from '../types';

export default function WatchDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { timezone } = usePreferences();
  const [watch, setWatch] = useState<Watch | null>(null);
  const [loading, setLoading] = useState(true);
  const [analyzing, setAnalyzing] = useState(false);
  const [analyzeError, setAnalyzeError] = useState('');
  const [detailsOpen, setDetailsOpen] = useState(false);
  const [pendingAnalysis, setPendingAnalysis] = useState<string | null>(null);

  useEffect(() => {
    if (!id) return;
    getWatch(Number(id))
      .then(setWatch)
      .catch(() => navigate('/'))
      .finally(() => setLoading(false));
  }, [id, navigate]);

  async function handleDelete() {
    if (!watch || !confirm('Delete this watch?')) return;
    await deleteWatch(watch.id);
    navigate('/');
  }

  async function handleDeleteImage(imageId: number) {
    if (!watch || !confirm('Delete this image?')) return;
    await deleteWatchImage(watch.id, imageId);
    setWatch({ ...watch, imageUrls: watch.imageUrls.filter((img) => img.id !== imageId) });
  }

  async function handleAnalyze() {
    if (!watch) return;
    setAnalyzing(true);
    setAnalyzeError('');
    try {
      const analysis = await analyzeWatch(watch.id);
      setPendingAnalysis(analysis);
    } catch {
      setAnalyzeError('Analysis failed. Check AI provider configuration in the admin panel.');
    } finally {
      setAnalyzing(false);
    }
  }

  async function handleAcceptAnalysis() {
    if (!watch || !pendingAnalysis) return;
    const newNotes = watch.notes
      ? `${watch.notes}\n\n---\n\n${pendingAnalysis}`
      : pendingAnalysis;
    await updateWatch(watch.id, {
      brand: watch.brand,
      model: watch.model,
      movementType: watch.movementType,
      caseSizeMm: watch.caseSizeMm,
      bandType: watch.bandType,
      bandColor: watch.bandColor,
      purchaseDate: watch.purchaseDate,
      purchasePrice: watch.purchasePrice,
      notes: newNotes,
      crystalType: watch.crystalType,
      caseShape: watch.caseShape,
      crownType: watch.crownType,
      calendarType: watch.calendarType,
      countryOfOrigin: watch.countryOfOrigin,
      waterResistance: watch.waterResistance,
      lugWidthMm: watch.lugWidthMm,
      dialColor: watch.dialColor,
      bezelType: watch.bezelType,
      powerReserveHours: watch.powerReserveHours,
      serialNumber: watch.serialNumber,
      batteryType: watch.batteryType,
      linkUrl: watch.linkUrl,
      linkText: watch.linkText,
      isWishList: watch.isWishList,
    });
    setWatch({ ...watch, notes: newNotes });
    setPendingAnalysis(null);
  }

  async function handleRecordWear() {
    if (!watch) return;
    const updated = await recordWear(watch.id);
    setWatch(updated);
  }

  function fmtDate(iso: string) {
    return new Date(iso).toLocaleDateString('en-US', { timeZone: timezone });
  }

  if (loading) return <p>Loading…</p>;
  if (!watch) return <p>Watch not found.</p>;

  return (
    <div className="watch-detail">
      <Link to="/" className="back-link">← Back</Link>
      <div className="watch-detail-header">
        <h1>{watch.brand} {watch.model}</h1>
        <div className="watch-detail-header-actions">
          <button className="btn btn-sm" onClick={handleRecordWear}>⌚ Wore Today</button>
          <Link to={`/watches/${watch.id}/edit`} className="btn btn-sm">Edit</Link>
          <button className="btn btn-danger btn-sm" onClick={handleDelete}>Delete</button>
        </div>
      </div>

      <div className="watch-detail-chips">
        <span className="detail-chip"><strong>Movement</strong> {watch.movementType}</span>
        {watch.caseSizeMm && <span className="detail-chip"><strong>Case</strong> {watch.caseSizeMm}mm</span>}
        {watch.bandType && <span className="detail-chip"><strong>Band</strong> {watch.bandType}</span>}
        {watch.bandColor && <span className="detail-chip"><strong>Band Color</strong> {watch.bandColor}</span>}
        {watch.purchaseDate && <span className="detail-chip"><strong>Purchased</strong> {fmtDate(watch.purchaseDate)}</span>}
        {watch.purchasePrice != null && <span className="detail-chip"><strong>Price</strong> ${watch.purchasePrice.toFixed(2)}</span>}
        <span className="detail-chip">
          <strong>Worn</strong> {watch.timesWorn} {watch.timesWorn === 1 ? 'time' : 'times'}
        </span>
        {watch.lastWornDate && (
          <span className="detail-chip"><strong>Last Worn</strong> {fmtDate(watch.lastWornDate)}</span>
        )}
        {watch.linkUrl && (
          <a href={watch.linkUrl} target="_blank" rel="noopener noreferrer" className="detail-chip" style={{ textDecoration: 'none' }}>
            <strong>Link</strong> {watch.linkText || watch.linkUrl}
          </a>
        )}
      </div>

      {(() => {
        const extras: { label: string; value: string }[] = [];
        if (watch.crystalType) extras.push({ label: 'Crystal', value: watch.crystalType });
        if (watch.caseShape) extras.push({ label: 'Case Shape', value: watch.caseShape });
        if (watch.crownType) extras.push({ label: 'Crown', value: watch.crownType });
        if (watch.calendarType) extras.push({ label: 'Calendar', value: watch.calendarType });
        if (watch.countryOfOrigin) extras.push({ label: 'Origin', value: watch.countryOfOrigin });
        if (watch.waterResistance) extras.push({ label: 'Water Resistance', value: watch.waterResistance });
        if (watch.lugWidthMm) extras.push({ label: 'Lug Width', value: `${watch.lugWidthMm}mm` });
        if (watch.dialColor) extras.push({ label: 'Dial', value: watch.dialColor });
        if (watch.bezelType) extras.push({ label: 'Bezel', value: watch.bezelType });
        if (watch.serialNumber) extras.push({ label: 'Serial / Ref', value: watch.serialNumber });
        if (watch.batteryType) extras.push({ label: 'Battery', value: watch.batteryType });
        if (extras.length === 0 && !watch.notes) return null;
        return (
          <div className="accordion" style={{ marginBottom: '1rem' }}>
            <button type="button" className="accordion-toggle" onClick={() => setDetailsOpen(!detailsOpen)}>
              Additional Details
              <span className={`accordion-chevron${detailsOpen ? ' open' : ''}`}>▼</span>
            </button>
            <div className={`accordion-content${detailsOpen ? ' open' : ''}`}>
              <div className="accordion-inner">
                {extras.length > 0 && (
                  <div className="watch-detail-chips" style={{ marginTop: '0.75rem' }}>
                    {extras.map((e) => (
                      <span key={e.label} className="detail-chip"><strong>{e.label}</strong> {e.value}</span>
                    ))}
                  </div>
                )}
                {watch.notes && (
                  <>
                    <h3 style={{ marginTop: '0.75rem' }}>Notes</h3>
                    <div className="watch-detail-notes watch-detail-notes-scroll">
                      <Markdown>{watch.notes}</Markdown>
                    </div>
                  </>
                )}
              </div>
            </div>
          </div>
        );
      })()}

      {watch.imageUrls.length > 0 && (
        <div className="watch-images-section">
          <ImageCarousel images={watch.imageUrls} alt={`${watch.brand} ${watch.model}`} />
          <div className="image-actions">
            <button className="btn btn-sm" onClick={handleAnalyze} disabled={analyzing}>
              {analyzing ? 'Analyzing…' : '🤖 Analyze with AI'}
            </button>
            <button className="btn btn-danger btn-sm" onClick={() => handleDeleteImage(watch.imageUrls[0]?.id)}>
              Delete Current Image
            </button>
          </div>
          {analyzeError && <p className="error">{analyzeError}</p>}
        </div>
      )}

      {pendingAnalysis !== null && (
        <div className="modal-overlay" onClick={() => setPendingAnalysis(null)}>
          <div className="modal analysis-modal" onClick={(e) => e.stopPropagation()}>
            <h3>AI Analysis</h3>
            <div className="analysis-modal-body">
              <Markdown>{pendingAnalysis}</Markdown>
            </div>
            <div className="modal-actions">
              <button className="btn" onClick={handleAcceptAnalysis}>Accept &amp; Save to Notes</button>
              <button className="btn btn-danger" onClick={() => setPendingAnalysis(null)}>Dismiss</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// src/web/src/pages/WatchDetailPage.vue
<template>
  <div>
    <RouterLink
      :to="watch?.isWishList ? '/?tab=wishlist' : '/'"
      class="text-accent text-sm hover:underline mb-4 inline-block"
    >
      ← Back
    </RouterLink>
    <div v-if="loading" class="flex justify-center py-20">
      <div class="w-8 h-8 border-2 border-accent border-t-transparent rounded-full animate-spin" />
    </div>
    <div v-else-if="watch" class="max-w-5xl mx-auto">
      <!-- Header -->
      <div class="relative mb-5 flex items-start justify-between gap-4">
        <div class="min-w-0">
          <p class="text-xs uppercase tracking-[0.24em] text-accent mb-2">{{ watch.isWishList ? 'Wish List' : watch.isRetired ? 'Retired' : 'Collection' }}</p>
          <h1 class="font-display text-3xl font-semibold text-text leading-tight"><span class="watch-brand">{{ watch.brand }}</span> {{ watch.model }}</h1>
        </div>
        <div class="relative flex-shrink-0">
          <button
            @click="actionsOpen = !actionsOpen"
            class="w-10 h-10 rounded-lg bg-bg-surface border border-border text-text text-xl leading-none hover:border-accent/50 transition-colors"
            aria-label="Watch actions"
          >
            …
          </button>
          <div v-if="actionsOpen" class="absolute right-0 top-12 z-30 w-56 bg-bg-card border border-border rounded-xl shadow-xl overflow-hidden">
            <template v-if="!watch.isWishList">
              <button @click="handleWearFromMenu" :disabled="wearLoading" class="menu-action text-accent">{{ wearLoading ? 'Recording...' : 'Wore Today' }}</button>
              <RouterLink :to="`/watches/${watch.id}/edit`" class="menu-action">Edit</RouterLink>
              <label class="menu-action cursor-pointer">
                {{ uploading ? 'Uploading…' : 'Upload Images' }}
                <input type="file" accept="image/*" multiple class="hidden" @change="handleImageUpload" :disabled="uploading" />
              </label>
              <button @click="handleAnalyzeFromMenu" :disabled="analyzing || !watch.imageUrls.length" class="menu-action">{{ analyzing ? 'Analyzing…' : 'AI Analyze' }}</button>
              <button @click="handleRefreshResaleFromMenu" :disabled="refreshingResale" class="menu-action">{{ refreshingResale ? 'Queuing…' : 'Refresh Resale' }}</button>
              <button v-if="!watch.isRetired" @click="handleRetireFromMenu" class="menu-action">Retire</button>
              <button @click="handleDeleteFromMenu" class="menu-action text-danger">Delete</button>
            </template>
            <template v-else>
              <button @click="handlePurchaseFromMenu" :disabled="purchasing" class="menu-action text-accent">{{ purchasing ? 'Moving…' : 'Mark Purchased' }}</button>
              <RouterLink :to="`/wishlist/${watch.id}/edit`" class="menu-action">Edit</RouterLink>
              <label class="menu-action cursor-pointer">
                {{ uploading ? 'Uploading…' : 'Upload Images' }}
                <input type="file" accept="image/*" multiple class="hidden" @change="handleImageUpload" :disabled="uploading" />
              </label>
              <button @click="handleDeleteFromMenu" class="menu-action text-danger">Delete</button>
            </template>
          </div>
        </div>
      </div>

      <!-- Image Gallery -->
      <div v-if="watch.imageUrls.length > 0" class="relative rounded-xl overflow-hidden bg-bg-surface mb-6">
        <div class="h-[300px] lg:h-[400px] flex items-center justify-center">
          <img
            :src="imageUrl(watch.imageUrls[imageIndex].url)"
            :alt="`${watch.brand} ${watch.model}`"
            class="max-w-full max-h-full object-contain"
          />
        </div>
        <div v-if="watch.imageUrls.length > 1" class="absolute bottom-3 inset-x-0 flex justify-center gap-1.5">
          <button
            v-for="(_, i) in watch.imageUrls"
            :key="i"
            @click="imageIndex = i"
            class="w-2 h-2 rounded-full transition-colors"
            :class="i === imageIndex ? 'bg-accent' : 'bg-white/40'"
          />
        </div>
      </div>

      <div v-if="watch.imageUrls.length > 0" class="flex flex-wrap gap-2 mb-6">
        <button
          @click="handleRemoveBackground"
          :disabled="removingBg"
          class="px-3 py-1.5 bg-bg-surface border border-border text-text-secondary text-xs rounded-lg hover:border-accent/50 transition-colors disabled:opacity-50"
        >
          {{ removingBg ? 'Removing…' : 'Remove Background' }}
        </button>
        <button
          @click="handleDeleteImage"
          class="px-3 py-1.5 bg-bg-surface border border-danger/50 text-danger text-xs rounded-lg hover:bg-danger/10 transition-colors"
        >
          Delete Image
        </button>
      </div>

      <section class="detail-card mb-6">
        <h2 class="detail-heading">Identification</h2>
        <dl class="detail-list">
          <DetailRow label="Brand" :value="watch.brand" />
          <DetailRow label="Model" :value="watch.model" />
          <DetailRow label="SKU / Reference" :value="watch.sku" />
          <DetailRow label="Serial" :value="watch.serialNumber" />
          <DetailRow label="Production Year" :value="watch.productionYear?.toString()" />
          <DetailRow label="Origin" :value="watch.countryOfOrigin" />
        </dl>
      </section>

      <section class="detail-card mb-6">
        <h2 class="detail-heading">Case &amp; Band</h2>
        <dl class="detail-list">
          <DetailRow label="Case Size" :value="watch.caseSizeMm ? `${watch.caseSizeMm} mm` : undefined" />
          <DetailRow label="Lug Width" :value="watch.lugWidthMm ? `${watch.lugWidthMm} mm` : undefined" />
          <DetailRow label="Case Shape" :value="watch.caseShape" />
          <DetailRow label="Crystal" :value="watch.crystalType" />
          <DetailRow label="Bezel" :value="watch.bezelType" />
          <DetailRow label="Crown" :value="watch.crownType" />
          <DetailRow label="Dial" :value="watch.dialColor" />
          <DetailRow label="Water Resistance" :value="watch.waterResistance" />
          <DetailRow label="Band Type" :value="watch.bandType" />
          <DetailRow label="Band Color" :value="watch.bandColor" />
        </dl>
      </section>

      <section class="detail-card mb-6">
        <h2 class="detail-heading">Movement</h2>
        <dl class="detail-list">
          <DetailRow label="Movement Type" :value="watch.movementType" />
          <DetailRow label="Power Reserve" :value="watch.powerReserveHours ? `${watch.powerReserveHours} hours` : undefined" />
          <DetailRow label="Calendar" :value="watch.calendarType" />
          <DetailRow label="Battery Type" :value="watch.batteryType" />
          <DetailRow label="Last Battery Changed" :value="formatFullDate(watch.lastBatteryChangedDate)" />
        </dl>
      </section>

      <section class="detail-card mb-6">
        <h2 class="detail-heading">Purchase Details</h2>
        <dl class="detail-list">
          <DetailRow :label="watch.isWishList ? 'Target Price' : 'Purchase Price'" :value="watch.purchasePrice ? `$${watch.purchasePrice.toFixed(2)}` : undefined" />
          <DetailRow label="Purchase Date" :value="formatFullDate(watch.purchaseDate)" />
          <DetailRow label="Current Resale" :value="watch.currentResaleValue ? `$${watch.currentResaleValue.toFixed(2)}` : undefined" />
          <DetailRow label="Resale Updated" :value="formatFullDate(watch.resaleValueUpdatedAt)" />
          <DetailRow
            label="Store Link"
            :value="watch.linkUrl ? (watch.linkText || 'Store Link') : undefined"
            :href="watch.linkUrl"
          />
        </dl>
      </section>

      <section class="detail-card mb-6">
        <h2 class="detail-heading">Ownership</h2>
        <dl class="detail-list">
          <DetailRow label="Storage" :value="watch.storageLocation" />
          <DetailRow v-if="!watch.isWishList" label="Wear Count" :value="watch.timesWorn.toString()" />
          <DetailRow v-if="!watch.isWishList" label="Last Worn" :value="formatFullDate(watch.lastWornDate)" />
          <DetailRow v-if="!watch.isWishList" label="Status" :value="watch.isRetired ? `Retired${retiredOn ? ` — ${retiredOn}` : ''}` : 'Active'" />
          <DetailRow label="Added" :value="formatFullDate(watch.createdAt)" />
          <DetailRow label="Last Updated" :value="formatFullDate(watch.updatedAt)" />
        </dl>
      </section>

      <!-- AI Analysis -->
      <section v-if="watch.aiAnalysis" class="detail-card mb-6">
        <h2 class="detail-heading">AI Analysis</h2>
        <div class="prose-markdown text-sm text-text" v-html="renderMarkdown(watch.aiAnalysis)" />
      </section>

      <!-- Resale Value History -->
      <section v-if="!watch.isWishList" class="detail-card mb-6">
        <div class="flex items-center justify-between mb-2">
          <h2 class="detail-heading !mb-0">Resale Value History</h2>
          <button @click="showManualResaleForm = !showManualResaleForm" class="text-xs text-accent hover:underline">
            {{ showManualResaleForm ? 'Cancel' : '+ Log Value' }}
          </button>
        </div>
        <p v-if="resaleError" class="text-xs text-danger mb-2">{{ resaleError }}</p>
        <p v-if="resaleQueuedMsg" class="text-xs text-success mb-2">{{ resaleQueuedMsg }}</p>

        <div v-if="showManualResaleForm" class="flex flex-wrap items-end gap-2 mb-4 p-3 bg-bg-surface border border-border rounded-lg">
          <div>
            <label class="block text-xs text-text-muted mb-1">Value</label>
            <input v-model.number="manualResaleValue" type="number" step="0.01" min="0" placeholder="0.00" class="w-28 px-2 py-1.5 bg-bg border border-border rounded-lg text-sm text-text" />
          </div>
          <div>
            <label class="block text-xs text-text-muted mb-1">Date</label>
            <input v-model="manualResaleDate" type="date" class="px-2 py-1.5 bg-bg border border-border rounded-lg text-sm text-text" />
          </div>
          <div class="flex-1 min-w-[8rem]">
            <label class="block text-xs text-text-muted mb-1">Notes</label>
            <input v-model="manualResaleNotes" type="text" placeholder="Optional" class="w-full px-2 py-1.5 bg-bg border border-border rounded-lg text-sm text-text" />
          </div>
          <button
            @click="handleAddManualResale"
            :disabled="savingManualResale || !manualResaleValue"
            class="px-3 py-1.5 bg-accent hover:bg-accent-hover text-bg text-sm font-medium rounded-lg transition-colors disabled:opacity-50"
          >
            {{ savingManualResale ? 'Saving…' : 'Save' }}
          </button>
        </div>

        <div v-if="resaleHistory.length === 0" class="text-sm text-text-muted">
          No resale value recorded yet — log one manually or refresh an estimate.
        </div>
        <div v-else class="space-y-2">
          <div v-for="entry in resaleHistory" :key="entry.id" class="flex items-start justify-between gap-3 text-sm">
            <div class="min-w-0">
              <span class="text-text font-medium">${{ entry.value.toFixed(2) }}</span>
              <span class="ml-2 px-1.5 py-0.5 rounded-full text-[10px] uppercase tracking-wide bg-bg-surface border border-border text-text-muted">
                {{ entry.source === 'Manual' ? 'Manual' : 'Web Estimate' }}
              </span>
              <span class="ml-2 text-xs text-text-muted">{{ new Date(entry.recordedAt).toLocaleDateString() }}</span>
              <p v-if="entry.reasoning" class="text-xs text-text-muted mt-0.5 truncate" :title="entry.reasoning">{{ entry.reasoning }}</p>
            </div>
            <button @click="handleDeleteResaleEntry(entry.id)" class="text-xs text-danger hover:underline flex-shrink-0">Remove</button>
          </div>
        </div>
      </section>

      <!-- Notes -->
      <section v-if="watch.notes" class="detail-card">
        <h2 class="detail-heading">Notes</h2>
        <div class="prose-markdown text-sm text-text" v-html="renderMarkdown(watch.notes)" />
      </section>
    </div>
    <div v-else class="text-center py-20 text-text-muted">Watch not found.</div>
  </div>
</template>

<script setup lang="ts">
import { computed, defineComponent, h, ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { marked } from 'marked'
import type { Watch, ResaleValueEntry } from '@/types'
import {
  getWatch, imageUrl, recordWear, retireWatch, deleteWatch, uploadImage, deleteImage, removeBackground,
  analyzeWatch, updateWatch, getResaleHistory, addManualResaleValue, deleteResaleValueEntry, refreshResaleValue,
} from '@/services/watches'

const route = useRoute()
const router = useRouter()

const DetailRow = defineComponent({
  props: {
    label: { type: String, required: true },
    value: { type: String, required: false, default: undefined },
    href: { type: String, required: false, default: undefined },
  },
  setup(props) {
    return () => h('div', { class: 'detail-row' }, [
      h('dt', { class: 'detail-label' }, props.label),
      h('dd', { class: props.value ? 'detail-value' : 'detail-value detail-empty' },
        props.value
          ? props.href
            ? [h('a', { href: props.href, target: '_blank', rel: 'noopener noreferrer', class: 'detail-link' }, `${props.value} ↗`)]
            : props.value
          : 'Not set'),
    ])
  },
})

function renderMarkdown(text: string): string {
  return marked.parse(text, { async: false }) as string
}

function formatFullDate(dateStr?: string): string | undefined {
  if (!dateStr) return undefined
  return new Date(dateStr).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })
}

const watch = ref<Watch | null>(null)
const retiredOn = computed(() => formatFullDate(watch.value?.retiredAt))
const loading = ref(true)
const imageIndex = ref(0)
const wearLoading = ref(false)
const uploading = ref(false)
const removingBg = ref(false)
const analyzing = ref(false)
const purchasing = ref(false)
const actionsOpen = ref(false)

const resaleHistory = ref<ResaleValueEntry[]>([])
const refreshingResale = ref(false)
const resaleError = ref('')
const resaleQueuedMsg = ref('')
const showManualResaleForm = ref(false)
const manualResaleValue = ref<number | null>(null)
const manualResaleDate = ref('')
const manualResaleNotes = ref('')
const savingManualResale = ref(false)

onMounted(async () => {
  try {
    watch.value = await getWatch(Number(route.params.id))
    if (watch.value && !watch.value.isWishList) {
      resaleHistory.value = await getResaleHistory(watch.value.id)
    }
  } finally {
    loading.value = false
  }
})

async function handleWear() {
  if (!watch.value) return
  wearLoading.value = true
  try {
    await recordWear(watch.value.id)
    watch.value.timesWorn++
  } finally {
    wearLoading.value = false
  }
}

async function handleWearFromMenu() {
  actionsOpen.value = false
  await handleWear()
}

async function handleRetireFromMenu() {
  actionsOpen.value = false
  await handleRetire()
}

async function handleDeleteFromMenu() {
  actionsOpen.value = false
  await handleDelete()
}

async function handlePurchaseFromMenu() {
  actionsOpen.value = false
  await handlePurchase()
}

async function handleAnalyzeFromMenu() {
  actionsOpen.value = false
  await handleAnalyze()
}

async function handleRefreshResaleFromMenu() {
  actionsOpen.value = false
  await handleRefreshResale()
}

async function handleRetire() {
  if (!watch.value || !confirm('Retire this watch?')) return
  await retireWatch(watch.value.id)
  router.push('/')
}

async function handleDelete() {
  if (!watch.value || !confirm('Delete this watch permanently?')) return
  const returnTo = watch.value.isWishList
    ? { path: '/', query: { tab: 'wishlist' } }
    : { path: '/' }
  await deleteWatch(watch.value.id)
  router.push(returnTo)
}

async function handlePurchase() {
  if (!watch.value || !confirm('Move this watch from your wish list to your collection?')) return
  purchasing.value = true
  try {
    const w = watch.value
    await updateWatch(w.id, {
      brand: w.brand,
      model: w.model,
      movementType: w.movementType,
      caseSizeMm: w.caseSizeMm,
      bandType: w.bandType,
      bandColor: w.bandColor,
      purchaseDate: w.purchaseDate,
      purchasePrice: w.purchasePrice,
      notes: w.notes,
      crystalType: w.crystalType,
      caseShape: w.caseShape,
      crownType: w.crownType,
      calendarType: w.calendarType,
      countryOfOrigin: w.countryOfOrigin,
      dialColor: w.dialColor,
      bezelType: w.bezelType,
      powerReserveHours: w.powerReserveHours,
      sku: w.sku,
      serialNumber: w.serialNumber,
      productionYear: w.productionYear,
      batteryType: w.batteryType,
      lastBatteryChangedDate: w.lastBatteryChangedDate,
      waterResistance: w.waterResistance,
      lugWidthMm: w.lugWidthMm,
      linkUrl: w.linkUrl,
      linkText: w.linkText,
      storageLocation: w.storageLocation,
      isWishList: false,
    })
    watch.value = await getWatch(w.id)
  } finally {
    purchasing.value = false
  }
}

async function handleImageUpload(e: Event) {
  if (!watch.value) return
  const files = (e.target as HTMLInputElement).files
  if (!files?.length) return
  uploading.value = true
  try {
    for (const file of Array.from(files)) {
      await uploadImage(watch.value.id, file)
    }
    watch.value = await getWatch(watch.value.id)
  } finally {
    uploading.value = false
    ;(e.target as HTMLInputElement).value = ''
  }
}

async function handleDeleteImage() {
  if (!watch.value || !watch.value.imageUrls[imageIndex.value]) return
  if (!confirm('Delete this image?')) return
  const img = watch.value.imageUrls[imageIndex.value]
  await deleteImage(watch.value.id, img.id)
  watch.value = await getWatch(watch.value.id)
  if (imageIndex.value >= watch.value.imageUrls.length) {
    imageIndex.value = Math.max(0, watch.value.imageUrls.length - 1)
  }
}

async function handleRemoveBackground() {
  if (!watch.value || !watch.value.imageUrls[imageIndex.value]) return
  removingBg.value = true
  try {
    const img = watch.value.imageUrls[imageIndex.value]
    await removeBackground(watch.value.id, img.id)
    watch.value = await getWatch(watch.value.id)
  } finally {
    removingBg.value = false
  }
}

async function handleAnalyze() {
  if (!watch.value || !watch.value.imageUrls[imageIndex.value]) return
  analyzing.value = true
  try {
    const img = watch.value.imageUrls[imageIndex.value]
    const analysis = await analyzeWatch(watch.value.id, img.id)
    watch.value.aiAnalysis = analysis
    watch.value = await getWatch(watch.value.id)
  } finally {
    analyzing.value = false
  }
}

async function handleRefreshResale() {
  if (!watch.value) return
  refreshingResale.value = true
  resaleError.value = ''
  resaleQueuedMsg.value = ''
  try {
    await refreshResaleValue(watch.value.id)
    resaleQueuedMsg.value = 'Refresh queued — check back in a bit for the updated value.'
  } catch (e: any) {
    resaleError.value = e?.response?.data?.error || 'Could not queue a resale value refresh.'
  } finally {
    refreshingResale.value = false
  }
}

async function handleAddManualResale() {
  if (!watch.value || manualResaleValue.value === null) return
  savingManualResale.value = true
  resaleError.value = ''
  try {
    watch.value = await addManualResaleValue(watch.value.id, {
      value: manualResaleValue.value,
      recordedAt: manualResaleDate.value || undefined,
      notes: manualResaleNotes.value || undefined,
    })
    resaleHistory.value = await getResaleHistory(watch.value.id)
    manualResaleValue.value = null
    manualResaleDate.value = ''
    manualResaleNotes.value = ''
    showManualResaleForm.value = false
  } finally {
    savingManualResale.value = false
  }
}

async function handleDeleteResaleEntry(entryId: number) {
  if (!watch.value || !confirm('Remove this resale value entry?')) return
  await deleteResaleValueEntry(entryId)
  resaleHistory.value = resaleHistory.value.filter(e => e.id !== entryId)
  watch.value = await getWatch(watch.value.id)
}
</script>

<style scoped>
/* PWA standalone runs at phone width, where "Brand Model" wraps mid-name.
   Give the brand its own line there; in a browser there is room to keep them inline. */
@media (display-mode: standalone) {
  .watch-brand {
    display: block;
  }
}

.detail-card {
  background: var(--color-bg-card);
  border: 1px solid var(--color-border);
  border-radius: 1rem;
  padding: 1.25rem;
  box-shadow: inset 0 1px 0 rgb(255 255 255 / 0.03);
}

.detail-heading {
  color: var(--color-accent);
  font-size: 0.8rem;
  font-weight: 700;
  letter-spacing: 0.22em;
  margin-bottom: 0.85rem;
  text-transform: uppercase;
}

.detail-list {
  display: grid;
  gap: 0;
}

:deep(.detail-row) {
  display: grid;
  grid-template-columns: minmax(8rem, 0.7fr) minmax(0, 1fr);
  gap: 1rem;
  padding: 0.85rem 0;
  border-bottom: 1px solid var(--color-border);
}

:deep(.detail-row:last-child) {
  border-bottom: 0;
}

:deep(.detail-label) {
  color: var(--color-text-secondary);
  font-size: 0.95rem;
}

:deep(.detail-value) {
  color: var(--color-text);
  font-size: 1rem;
  min-width: 0;
  overflow-wrap: anywhere;
}

:deep(.detail-empty) {
  color: var(--color-text-muted);
}

:deep(.detail-link) {
  color: var(--color-accent);
}

:deep(.detail-link:hover) {
  text-decoration: underline;
}

.menu-action {
  display: block;
  width: 100%;
  padding: 0.75rem 1rem;
  text-align: left;
  color: var(--color-text);
  font-size: 0.9rem;
  font-weight: 500;
  white-space: nowrap;
  transition: background-color 0.15s ease, color 0.15s ease;
}

.menu-action:hover {
  background: var(--color-bg-surface);
  color: var(--color-accent);
}

.menu-action:disabled {
  opacity: 0.55;
  cursor: not-allowed;
}

@media (min-width: 768px) {
  .detail-card {
    padding: 1.5rem 1.75rem;
  }
}
</style>
