// src/web/src/components/common/WatchForm.vue
<template>
  <form @submit.prevent="emit('submit', formData)" class="space-y-4 max-w-lg">
    <div class="grid grid-cols-2 gap-4">
      <div class="col-span-2 sm:col-span-1">
        <label class="block text-sm font-medium text-text-secondary mb-1">Brand *</label>
        <input v-model="formData.brand" required class="w-full px-4 py-3 bg-bg-surface border border-border rounded-lg text-text placeholder:text-text-muted focus:outline-none focus:border-accent transition-colors" />
      </div>
      <div class="col-span-2 sm:col-span-1">
        <label class="block text-sm font-medium text-text-secondary mb-1">Model *</label>
        <input v-model="formData.model" required class="w-full px-4 py-3 bg-bg-surface border border-border rounded-lg text-text placeholder:text-text-muted focus:outline-none focus:border-accent transition-colors" />
      </div>
    </div>

    <div>
      <label class="block text-sm font-medium text-text-secondary mb-1">Movement *</label>
      <select v-model="formData.movementType" required class="w-full px-4 py-3 bg-bg-surface border border-border rounded-lg text-text focus:outline-none focus:border-accent transition-colors">
        <option value="Automatic">Automatic</option>
        <option value="Manual">Manual</option>
        <option value="Quartz">Quartz</option>
        <option value="Digital">Digital</option>
      </select>
    </div>

    <div class="grid grid-cols-2 gap-4">
      <div>
        <label class="block text-sm font-medium text-text-secondary mb-1">Case Size (mm)</label>
        <input v-model.number="formData.caseSizeMm" type="number" class="w-full px-4 py-3 bg-bg-surface border border-border rounded-lg text-text focus:outline-none focus:border-accent transition-colors" />
      </div>
      <div>
        <label class="block text-sm font-medium text-text-secondary mb-1">Band Type</label>
        <input v-model="formData.bandType" class="w-full px-4 py-3 bg-bg-surface border border-border rounded-lg text-text focus:outline-none focus:border-accent transition-colors" />
      </div>
    </div>

    <div class="grid grid-cols-2 gap-4">
      <div>
        <label class="block text-sm font-medium text-text-secondary mb-1">Band Color</label>
        <input v-model="formData.bandColor" class="w-full px-4 py-3 bg-bg-surface border border-border rounded-lg text-text focus:outline-none focus:border-accent transition-colors" />
      </div>
      <div>
        <label class="block text-sm font-medium text-text-secondary mb-1">Dial Color</label>
        <input v-model="formData.dialColor" class="w-full px-4 py-3 bg-bg-surface border border-border rounded-lg text-text focus:outline-none focus:border-accent transition-colors" />
      </div>
    </div>

    <div class="grid grid-cols-2 gap-4">
      <div>
        <label class="block text-sm font-medium text-text-secondary mb-1">Purchase Date</label>
        <input v-model="formData.purchaseDate" type="date" class="w-full px-4 py-3 bg-bg-surface border border-border rounded-lg text-text focus:outline-none focus:border-accent transition-colors" />
      </div>
      <div>
        <label class="block text-sm font-medium text-text-secondary mb-1">Purchase Price</label>
        <input v-model.number="formData.purchasePrice" type="number" step="0.01" class="w-full px-4 py-3 bg-bg-surface border border-border rounded-lg text-text focus:outline-none focus:border-accent transition-colors" />
      </div>
    </div>

    <div>
      <label class="block text-sm font-medium text-text-secondary mb-1">Notes</label>
      <textarea v-model="formData.notes" rows="3" class="w-full px-4 py-3 bg-bg-surface border border-border rounded-lg text-text placeholder:text-text-muted focus:outline-none focus:border-accent transition-colors resize-none" />
    </div>

    <div class="grid grid-cols-2 gap-4">
      <div>
        <label class="block text-sm font-medium text-text-secondary mb-1">Crystal Type</label>
        <input v-model="formData.crystalType" class="w-full px-4 py-3 bg-bg-surface border border-border rounded-lg text-text focus:outline-none focus:border-accent transition-colors" />
      </div>
      <div>
        <label class="block text-sm font-medium text-text-secondary mb-1">Water Resistance</label>
        <input v-model="formData.waterResistance" class="w-full px-4 py-3 bg-bg-surface border border-border rounded-lg text-text focus:outline-none focus:border-accent transition-colors" />
      </div>
    </div>

    <div>
      <label class="block text-sm font-medium text-text-secondary mb-1">Link URL</label>
      <input v-model="formData.linkUrl" type="url" class="w-full px-4 py-3 bg-bg-surface border border-border rounded-lg text-text focus:outline-none focus:border-accent transition-colors" placeholder="https://..." />
    </div>

    <button type="submit" :disabled="loading" class="w-full py-3 bg-accent hover:bg-accent-hover text-bg font-semibold rounded-lg transition-colors disabled:opacity-50 mt-6">
      {{ loading ? 'Saving...' : 'Save Watch' }}
    </button>
  </form>
</template>

<script setup lang="ts">
import { reactive } from 'vue'
import type { CreateWatch } from '@/types'

const props = defineProps<{
  initial?: CreateWatch
  loading?: boolean
}>()

const emit = defineEmits<{
  submit: [data: CreateWatch]
}>()

const formData = reactive<CreateWatch>({
  brand: props.initial?.brand || '',
  model: props.initial?.model || '',
  movementType: props.initial?.movementType || 'Automatic',
  caseSizeMm: props.initial?.caseSizeMm,
  bandType: props.initial?.bandType || '',
  bandColor: props.initial?.bandColor || '',
  purchaseDate: props.initial?.purchaseDate || '',
  purchasePrice: props.initial?.purchasePrice,
  notes: props.initial?.notes || '',
  crystalType: props.initial?.crystalType || '',
  dialColor: props.initial?.dialColor || '',
  waterResistance: props.initial?.waterResistance || '',
  linkUrl: props.initial?.linkUrl || '',
})
</script>

// src/web/src/components/WatchForm.tsx
import { useState, type FormEvent, type ChangeEvent } from 'react';
import type { CreateWatch, MovementType } from '../types';

interface WatchFormProps {
  initial?: Partial<CreateWatch>;
  onSubmit: (data: CreateWatch, files: File[]) => void;
  submitLabel?: string;
}

const MOVEMENT_TYPES: MovementType[] = ['Automatic', 'Manual', 'Quartz', 'Digital'];
const BAND_TYPE_OPTIONS = ['Black Leather', 'Brown Leather', 'Titanium'];

export default function WatchForm({ initial, onSubmit, submitLabel = 'Save' }: WatchFormProps) {
  const [brand, setBrand] = useState(initial?.brand ?? '');
  const [model, setModel] = useState(initial?.model ?? '');
  const [movementType, setMovementType] = useState<MovementType>(initial?.movementType ?? 'Automatic');
  const [caseSizeMm, setCaseSizeMm] = useState(initial?.caseSizeMm?.toString() ?? '');

  const initialBand = initial?.bandType ?? '';
  const isPreset = BAND_TYPE_OPTIONS.includes(initialBand);
  const [bandTypeSelect, setBandTypeSelect] = useState(isPreset ? initialBand : initialBand ? 'Custom' : '');
  const [bandTypeCustom, setBandTypeCustom] = useState(isPreset ? '' : initialBand);

  const [purchaseDate, setPurchaseDate] = useState(initial?.purchaseDate?.substring(0, 10) ?? '');
  const [purchasePrice, setPurchasePrice] = useState(initial?.purchasePrice?.toString() ?? '');
  const [notes, setNotes] = useState(initial?.notes ?? '');
  const [files, setFiles] = useState<File[]>([]);

  function handleFileChange(e: ChangeEvent<HTMLInputElement>) {
    if (e.target.files) {
      const selected = Array.from(e.target.files);
      setFiles((prev) => [...prev, ...selected]);
      e.target.value = '';
    }
  }

  function handleSubmit(e: FormEvent) {
    e.preventDefault();
    const bandType = bandTypeSelect === 'Custom' ? bandTypeCustom : bandTypeSelect;
    const data: CreateWatch = {
      brand,
      model,
      movementType,
      ...(caseSizeMm && { caseSizeMm: Number(caseSizeMm) }),
      ...(bandType && { bandType }),
      ...(purchaseDate && { purchaseDate }),
      ...(purchasePrice && { purchasePrice: Number(purchasePrice) }),
      ...(notes && { notes }),
    };
    onSubmit(data, files);
  }

  return (
    <form className="watch-form" onSubmit={handleSubmit}>
      <fieldset className="watch-form-group">
        <legend>Watch Details</legend>
        <div className="watch-form-row">
          <label>
            Brand *
            <input value={brand} onChange={(e) => setBrand(e.target.value)} required />
          </label>
          <label>
            Model *
            <input value={model} onChange={(e) => setModel(e.target.value)} required />
          </label>
        </div>
        <div className="watch-form-row">
          <label>
            Movement Type *
            <select value={movementType} onChange={(e) => setMovementType(e.target.value as MovementType)}>
              {MOVEMENT_TYPES.map((mt) => (
                <option key={mt} value={mt}>{mt}</option>
              ))}
            </select>
          </label>
          <label>
            Case Size (mm)
            <input type="number" value={caseSizeMm} onChange={(e) => setCaseSizeMm(e.target.value)} />
          </label>
        </div>
        <div className="watch-form-row">
          <label>
            Band Type
            <select value={bandTypeSelect} onChange={(e) => setBandTypeSelect(e.target.value)}>
              <option value="">— Select —</option>
              {BAND_TYPE_OPTIONS.map((bt) => (
                <option key={bt} value={bt}>{bt}</option>
              ))}
              <option value="Custom">Custom…</option>
            </select>
          </label>
          {bandTypeSelect === 'Custom' && (
            <label>
              Custom Band Type
              <input value={bandTypeCustom} onChange={(e) => setBandTypeCustom(e.target.value)} />
            </label>
          )}
        </div>
      </fieldset>

      <fieldset className="watch-form-group">
        <legend>Purchase Info</legend>
        <div className="watch-form-row">
          <label>
            Purchase Date
            <input type="date" value={purchaseDate} onChange={(e) => setPurchaseDate(e.target.value)} />
          </label>
          <label>
            Purchase Price
            <input type="number" step="0.01" value={purchasePrice} onChange={(e) => setPurchasePrice(e.target.value)} />
          </label>
        </div>
      </fieldset>

      <fieldset className="watch-form-group">
        <legend>Additional</legend>
        <label>
          Notes
          <textarea value={notes} onChange={(e) => setNotes(e.target.value)} />
        </label>
        <label>
          Images
          <input type="file" accept="image/*" multiple onChange={handleFileChange} />
        </label>
        {files.length > 0 && <p className="file-count">{files.length} file(s) selected</p>}
      </fieldset>

      <button type="submit">{submitLabel}</button>
    </form>
  );
}
